env:
  es6: true
  node: true
extends:
  - eslint:recommended
  - airbnb-base
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  curly: error
  eqeqeq: error
  linebreak-style:
    - error
    - unix
  no-console: 'off'
  no-var: error
  prefer-const: error
  semi:
    - error
    - always
  prettier/prettier:
    - error
    -
      singleQuote: true
      trailingComma: all
