env:
  es6: true
  node: true
extends:
  - eslint:recommended
  - airbnb-base
  - plugin:node/recommended
  - plugin:promise/recommended
  - plugin:prettier/recommended
plugins:
  - promise
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  prettier/prettier: error
overrides:
  - files: scripts/**/*.js
    rules:
      import/no-extraneous-dependencies:
        - error
        - devDependencies: true
  - files: '**/*.mjs'
    rules:
      no-restricted-globals:
        - error
        - name: __dirname
        - name: __filename
        - name: exports
        - name: module
        - name: require
      import/no-commonjs: error
      node/no-unsupported-features/es-syntax:
        - error
        - ignores:
            - modules
