extends:
  - eslint:recommended
  - airbnb-base
  - plugin:@typescript-eslint/recommended
  - plugin:import/typescript
  - plugin:prettier/recommended
  - prettier/@typescript-eslint
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
  project: ./tsconfig.json
plugins:
  - '@typescript-eslint'
rules:
  node/no-unsupported-features/es-syntax:
    - error
    - ignores:
        - modules
  '@typescript-eslint/explicit-function-return-type':
    - warn
    - allowExpressions: true
  prettier/prettier:
    - error
    - tabWidth: 4
