env:
  es6: true
  node: true
extends:
  - eslint:recommended
  - airbnb-base
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  prettier/prettier: error
overrides:
  - files: scripts/**/*.js
    rules:
      import/no-extraneous-dependencies:
        - error
        - devDependencies: true
